# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0003_auto_20170227_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='days_since_visited',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='place',
            name='date_visited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
